language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
deploy:
  provider: script
  script: yarn install && yarn run deploy
  skip_cleanup: true
  # keep-history: false
  fqdn: reettalipponen.art
  on:
    branch: master