fragment HomeParts on Home {
  __typename
  title
  description
  body
}

fragment WorksParts on Works {
  __typename
  title
  description
  slug
  gallery {
    __typename
    image
    title
  }
}

fragment CvParts on Cv {
  __typename
  title
  description
  sections {
    __typename
    sectionTitle
    entries {
      __typename
      date
      content
    }
  }
}

fragment ContactParts on Contact {
  __typename
  title
  description
  body
}
